name: Deploy policy_simulation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: prestij-khairunnisa-policy
          workload_identity_provider: projects/9576107772/locations/global/workloadIdentityPools/github-actions-pool/providers/github
          service_account: github-actions-policy@prestij-khairunnisa-policy.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t asia-southeast1-docker.pkg.dev/prestij-khairunnisa-policy/policy-simulation/policy-simulation:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            asia-southeast1-docker.pkg.dev/prestij-khairunnisa-policy/policy-simulation/policy-simulation:${{ github.sha }}
